name: hedgedoc
services:
  database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${HEDGEDOC_VOLUME}:/var/lib/postgresql/data
    restart: always
  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:latest
    environment:
      - CMD_DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - CMD_DOMAIN=localhost # use FQDN if use for production
      - CMD_URL_ADDPORT=true # if use FQDN remove this line
    volumes:
      - ${HEDGEDOC_VOLUME}/uploads:/hedgedoc/public/uploads
    ports:
      - "3005:3000"
    restart: always
    depends_on:
      - database
volumes:
  database:
  uploads: