services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3333:3000
    environment:
      - TRUST_PROXY=false # Set to true if a reverse proxy is in front of the container
    volumes:
      - ${MEDIA_PATH}/data:/opt/app/backend/data # use your NAS drive or something
      - ${CONFIG}/pingvin/images:/opt/app/frontend/public/img
  # To add ClamAV, to scan your shares for malicious files, 
  # see https://stonith404.github.io/pingvin-share/setup/integrations/#clamav-docker-only