services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - 8084:8080
    volumes:
      - ${CONFIG}/sterlingpdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ${CONFIG}/sterlingpdf/extraConfigs:/configs
      - ${CONFIG}/sterlingpdf/customFiles:/customFiles/
    #      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
