services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_MYSQL_HOST: ${DB_MYSQL_HOST}
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${DB_MYSQL_NAME}
      # DISABLE_IPV6: 'true'
    volumes:
      - ${CONFIG}/data:/data
      - ${CONFIG}/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - frontend

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ${CONFIG}/mysql:/var/lib/mysql
    networks:
      - frontend
networks:
  frontend:
    driver: bridge